cicerotapi/urls.py
# -*- coding: utf-8 *-*
from django.conf.urls import url, include
from django.contrib.auth.views import  password_reset_done, password_reset_complete
from django.conf.urls import url, include, i18n
from django.contrib import admin, admindocs
from django.conf import settings
from django.views.static import serve
from rest_framework import routers
from cicerotapi import views
import oauth2_provider.views as oauth2_views
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet


router = routers.DefaultRouter()
router.register(r'Region',views.RegionViewSet)
router.register(r'Provincia',views.ProvinciaViewSet)
router.register(r'Comuna',views.ComunaViewSet)
router.register(r'TipoTag',views.TipoTagViewSet)
router.register(r'Tag',views.TagViewSet)
router.register(r'EstadoTour',views.EstadoTourViewSet)
router.register(r'TipoTour',views.TipoTourViewSet)
router.register(r'TipoGuia',views.TipoGuiaViewSet)
router.register(r'RegistroGuia',views.RegistroGuiaViewSet)
router.register(r'Guia',views.GuiaViewSet)
router.register(r'Tour',views.TourViewSet)	
router.register(r'Horario',views.HorarioViewSet)
router.register(r'Pais',views.PaisViewSet)
router.register(r'Turista',views.TuristaViewSet)
router.register(r'Actividad',views.ActividadViewSet)
router.register(r'Rol',views.RolViewSet)
router.register(r'TextoSelect',views.TextoSelectViewSet)
router.register(r'Evaluacion',views.EvaluacionViewSet)
router.register(r'TipoMultimedia',views.TipoMultimediaViewSet)	
router.register(r'Multimedia',views.MultimediaViewSet)
router.register(r'Staff',views.StaffViewSet)
router.register(r'Favorito',views.FavoritoViewSet)
router.register(r'Suscripción',views.SuscripcionViewSet)
router.register(r'Transaccion',views.TransaccionViewSet)
router.register(r'InstanciaTour',views.InstanciaTourViewSet)
router.register(r'Inscripcion',views.InscripcionViewSet)
router.register(r'TipoServicio',views.TipoServicioViewSet)
router.register(r'ServicioTour',views.ServicioTourViewSet)
router.register(r'Comentario',views.ComentarioViewSet)
router.register(r'FCMDevice',views.FCMDeviceViewSet)			
 

urlpatterns = [
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^devices?$', FCMDeviceAuthorizedViewSet.as_view({'post': 'create'}), name='create_fcm_device'),
    url(r'^',include(router.urls)), 
]

cicerotproject/urls.py
from django.conf.urls import url, include, i18n
from django.contrib import admin, admindocs
from django.conf import settings
from django.views.static import serve
from rest_framework import routers
from cicerotapi import urls

admin.autodiscover()

urlpatterns = [
    
    # Admin views
    url(r'^admin/', admin.site.urls),
    # CiceroT web views
    url(r'^', include('cicerotwebapp.urls', namespace='cicerotwebapp')),

    # Other views
    url(r'^i18n/', include(i18n)),
    url(r'^media/(?P<path>.*)$', serve , { 'document_root': settings.MEDIA_ROOT }),
    url(r'^static/(?P<path>.*)$', serve , { 'document_root':settings.STATIC_ROOT }),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    # API URLS
    url(r'^api/', include('cicerotapi.urls', namespace='api')),
]

cicerotwebapp/urls.py
# -*- coding: utf-8 *-*
from django.conf.urls import url, include
from cicerotwebapp.views import general_views
from django.contrib.auth.views import  password_reset_done, password_reset_complete

urlpatterns = [
      # Home
      url(r'^$', general_views.Home, name= "home"), 
      url(r'^about_us/$', general_views.AboutUs, name="aboutUs"),
      url(r'^faqs/$', general_views.FAQs, name="faqs"),
      url(r'^servicios/$', general_views.OurServices, name="servicios"),
      url(r'^contact_us/$', general_views.ContactUs, name="contactUs"),


      # SERVICIOS
      url(r'^guias/$', general_views.GetAllGuias, name="GetAllGuias"),
      url(r'^guias/perfil/(?P<id>\d+)/$', general_views.GetGuia, name="GetGuia"),

      url(r'^tour/detalle/(?P<id>\d+)/$', general_views.GetTour, name="GetTour"),
      url(r'^tours/$', general_views.GetAllTours, name="GetAllTours"),

      url(r'^lugares/', general_views.GetAllLugares, name="GetAllLugares"),
      url(r'^toureg/', general_views.GetTour, name="GetTour"),

]

cicerotwebapp/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-

# Librerias.
import os, sys
from django.db import models
from django.contrib import auth
from django_resized import ResizedImageField
from django.utils import timezone
from datetime import datetime, timedelta
from django.db.models import Q

class Region(models.Model):
	# SIMPLE FLIELD
	nombre_region = models.CharField(max_length=100, verbose_name="Nombre")
	sigla_region = models.CharField(max_length=100, verbose_name="Sigla")

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s Región %s" % (self.sigla_region, self.nombre_region)

class Provincia(models.Model):
	# SIMPLE FIELD
	nombre_provincia = models.CharField(max_length=100, verbose_name="Nombre")

	# RELATION FIELD
	region = models.ForeignKey(Region, verbose_name="Región")
	
	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "[%s] %s, %s" % (self.id, self.region.sigla_region, self.nombre_provincia)

class Comuna(models.Model):
	# SIMPLE FIELD
	nombre_comuna = models.CharField(max_length=100, verbose_name="Nombre")

	# RELATION FIELD
	provincia = models.ForeignKey(Provincia, verbose_name="Provincia")
	
	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")
	
	def __str__(self):
		return "%s - %s" % (self.provincia.region.sigla_region, self.nombre_comuna)

class TipoTag(models.Model):
	#SIMPLE FIELD
	nombre_tipo_tag = models.CharField(max_length=100, verbose_name="Nombre", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_tipo_tag)
		

class Tag(models.Model):
	# SIMPLE FIELD
	texto_tag = models.CharField(max_length=100, verbose_name="Tag", null=True, blank=True)

	# RELATION FIELD
	tipo_tag = models.ForeignKey(TipoTag, verbose_name="Tipo de Tag", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")


	def __str__(self):
		return "%s" % (self.texto_tag)

class EstadoTour(models.Model):
	# SIMPLE FIELD
	nombre_estado_tour = models.CharField(max_length=100, verbose_name="Nombre", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_estado_tour)

class TipoTour(models.Model):
	# SIMPLE FIELD
	nombre_tipo_tour = models.CharField(max_length=100, verbose_name="Nombre", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_tipo_tour)	
	
class TipoGuia(models.Model):
	# SIMPLE FIELD
	nombre_tipo_guia = models.CharField(max_length=100, verbose_name="Nombre", null=True, blank=True)
		
	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_tipo_guia)

class RegistroGuia(models.Model):
	# SIMPLE FIELD
	direccion_guia_registro = models.CharField(max_length=255, verbose_name="Dirección Guia", null=True, blank=True)
	direccion_representante_legal_registro = models.CharField(max_length=255, verbose_name="Dirección Representante legal", null=True, blank=True)
	razon_social_guia_registro = models.CharField(max_length=255, verbose_name="Razón social", null=True, blank=True)
	representante_legal_guia_registro = models.CharField(max_length=255, verbose_name="Representante legal", null=True, blank=True)
	nombre_fantasia_guia_registro = models.CharField(max_length=255, verbose_name="Nombre", null=True, blank=True)
	es_sello_q_registro = models.BooleanField(default=False, verbose_name="¿Tiene sello Q?", blank=True)
	tipo_sello_q_registro = models.CharField(max_length=255, verbose_name="Tipo sello", null=True, blank=True)
	inicio_sello_q_registro = models.DateTimeField(verbose_name="Fecha inicio sello Q", null=True, blank=True)
	fin_sello_q_registro = models.DateTimeField(verbose_name="Fecha fin sello Q", null=True, blank=True)
	tipo_personalidad_registro = models.CharField(max_length=255, verbose_name="Personalidad Jurídica", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_fantasia_guia_registro)

class Guia(models.Model):
	# SIMPLE FIELD
	descripcion_guia = models.TextField(max_length=400, verbose_name="Descripción Guia", blank=True, null=True)
	clasificacion_guia = models.CharField(max_length=100, verbose_name="Clasificación", null=True, blank=True)
	rut_guia = models.CharField(max_length=100, verbose_name="Rut", null=True, blank=True)
	telefono_guia = models.CharField(max_length=100, verbose_name="Teléfono guia", null=True, blank=True)
	celular_guia = models.CharField(max_length=100, verbose_name="Celular guia", null=True, blank=True)

	# RELATION FIELD
	tags = models.ManyToManyField(Tag, related_name="guia", verbose_name="Tags guía", blank=True)
	tipos_guia = models.ManyToManyField(TipoGuia, related_name="guia", verbose_name="Tipos guía", blank=True)
	registro = models.OneToOneField(RegistroGuia, related_name="guia", verbose_name="Registro guía", blank=True, null=True)
	usuario = models.OneToOneField(auth.models.User, verbose_name="Usuario", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.descripcion_guia)

	
class Tour(models.Model):
	# SIMPLE FIELD
	nombre_tour = models.CharField(max_length=100, verbose_name="Nombre Tour", null=True, blank=True)
	descripcion_tour = models.TextField(max_length=400, verbose_name="Descripción Tour", blank=True, null=True)
	capacidad_tour = models.IntegerField(verbose_name="Capacidad Tour", null=True, blank=True) 
	precio_tour = models.IntegerField(verbose_name="Precio Tour", null=True, blank=True) 
	es_oferta = models.BooleanField(default=False, verbose_name="¿Tour en oferta?", blank=True)
	latitud = models.CharField(max_length=100, verbose_name="Latitud", null=True, blank=True)
	longitud = models.CharField(max_length=100, verbose_name="Longitud", null=True, blank=True)

	# RELATION FIELD
	tipo_tour = models.ForeignKey(TipoTour, verbose_name="Tipo tour", null=True, blank=True) 
	estado_tour = models.ForeignKey(EstadoTour, verbose_name="Estado Tour", null=True, blank=True)
	comunas = models.ManyToManyField(Comuna, related_name="tour", verbose_name="Comunas tour", blank=True)
	tags = models.ManyToManyField(Tag, related_name="tour", verbose_name="Tags tour", blank=True)
	guia = models.ForeignKey(Guia, related_name="tour", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_tour)
		
class Horario(models.Model):
	# SIMPLE FIELD
	inicio_horario = models.DateTimeField(verbose_name="Fecha inicio", null=True, blank=True)
	fin_horario = models.DateTimeField(verbose_name="Fecha fin", null=True, blank=True)

	# RELATION FIELD
	tour = models.ForeignKey(Tour, verbose_name="Horario Tour", null=True, blank=True)
	
	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "Inicio %s - Fin %s" % (str(self.inicio_horario),str(self.fin_horario))

class Pais(models.Model):
	# SIMPLE FIELD
	nombre_pais = models.CharField(max_length=255, verbose_name="Nombre", null=True, blank=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")

	def __str__(self):
		return "%s" % (self.nombre_pais)

class Turista(models.Model):
	# SIMPLE FIELD
	descripcion_turista = models.TextField(max_length=400, verbose_name="Descripción Turista", blank=True, null=True)

	# RELATION FIELD
	usuario = models.OneToOneField(auth.models.User, verbose_name="usuario", blank=True, null=True)
	pais = models.ForeignKey(Pais, verbose_name="Pais", blank=True, null=True)

	# TIMESTAMP FIELD
	created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Fecha creación")
	updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Fecha última modificación")
	

cicerotwebapp/forms/general_forms.py
from django import forms
from cicerotwebapp import models
from django.contrib import auth
from django.contrib.auth.models import User

class MensajeContactoForm(forms.ModelForm):
	class Meta:
		model = models.MensajeContacto
		fields = ["nombre",
				  "email",
				  "asunto",
				  "mensaje"]

	def __init__(self, *a, **kw):
		super(MensajeContactoForm, self).__init__(*a, **kw)
		self.fields['texto'].required = True 
		self.fields['nombre'].required = True 
		self.fields['email'].required = True
		self.fields['tipo'].required = True

cicerotwebapp/templates/guia.html
{% extends "home.html" %}
<!-- field atributes modificaciones / atributo concreto form.nombre-->
{{ form.media.css }}

{% load static %}

{{ form.media.css }}

{% block content %}

    <!-- Start Page Banner -->
    <div class="page-banner" style="padding:40px 0; background: url('{% static 'margo/images/slide-02-bg.jpg'%}') center #f9f9f9;">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Guia</h2>
            <p>Perfil Guía Turístico</p>
          </div>
          <div class="col-md-6">
            <ul class="breadcrumbs">
              <li><a href="{% url 'cicerotwebapp:home' %}">Home</a></li>
              <li>Perfil Guía</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- End Page Banner -->


    <!-- Start Content -->
    <div id="content">
      <div class="container">
        <div class="page-content">


          <div class="row">

            <div class="col-md-3">

              <!-- Classic Heading -->
              <h4 class="classic-title"><span>Perfil del guía</span></h4>
              <div class="team-member">
                <!-- Memebr Photo, Name & Position -->
                <div class="member-photo">
                  <img alt="" src="{{guia.usuario.multimedia_set.all.0.archivo_multimedia.url}}" />
                  <div class="member-name">{{guia.usuario.first_name}} {{guia.usuario.last_name}} - {{guia.clasificacion_guia}} <i class="fa fa-star"></i> <span>Guía Turístico</span></div>
                </div>
                <!-- Memebr Words -->
                <div class="member-info">
                  <p class="">{{guia.descripcion_guia}}</p>...
                </div>
                <!-- Memebr Social Links -->
                <div class="member-socail">
                  <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                  <a class="gplus" href="#"><i class="fa fa-google-plus"></i></a>
                  <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                  <a class="flickr" href="#"><i class="fa fa-flickr"></i></a>
                  <a class="mail" href="#"><i class="fa fa-envelope"></i></a>
                </div>
                <div class="member-info">
                  Etiquetas: {% for tag in guia.tags.all %}
                    <a href="#">{{tag.texto_tag}}</a>,
                  {% endfor %}
                </div>
                <div class="member-info">
                  Tipo de Guía: {% for tipo in guia.tipos_guia.all %}
                    <a href="#">{{tipo.nombre_tipo_guia}}</a>,
                  {% endfor %}
                </div>
              </div>
              <!-- Some Text -->
              
              <p> </p>

            </div>

            <div class="col-md-9">

             <div class="panel-group" id="accordion">
 
                <div class="panel panel-default">
                <div class="panel-heading">
                <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse-4">
                <i class="fa fa-angle-up control-icon"></i>
                <i class="fa fa-info"></i> Información Guia
                </a>
                </h4>
                </div>
                <div id="collapse-4" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul>
                   <li><i class="fa fa-caret-right"></i> Nombre: {{guia.usuario.first_name}} {{guia.usuario.last_name}}</li>
                   <li><i class="fa fa-caret-right"></i> Ciudad: Santigo - Región: Metropolitana</li>
                   <li><i class="fa fa-caret-right"></i> Idiomas: Español </li>
                   <li><i class="fa fa-caret-right"></i> Rut: {{guia.rut}}</li>
                   <li><i class="fa fa-caret-right"></i> Télefono: {{guia.telefono_guia}}</li>
                   <li><i class="fa fa-caret-right"></i> Télefono: {{celular.celular_guia}}</li>
                   <li><i class="fa fa-caret-right"></i> Rut: {{guia.rut}}</li>
                  </ul>
                  

                </div>
                </div>
                </div>

                 <div class="panel panel-default">
                <div class="panel-heading">
                <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse-3">
                <i class="fa fa-angle-up control-icon"></i>
                <i class="fa fa-info"></i> Registro Guía
                </a>
                </h4>
                </div>
                <div id="collapse-3" class="panel-collapse collapse in">
                <div class="panel-body">
                  <ul>
                   <li><i class="fa fa-caret-right"></i> Dirección Guía: {{guia.registro.direccion_guia_registro}}</li>
                   <li><i class="fa fa-caret-right"></i> Razon social: {{guia.registro.razon_social_guia_registro}}</li>
                   <li><i class="fa fa-caret-right"></i> Representante legal: {{guia.registro.representante_legal_guia_registro}} </li>
                   <li><i class="fa fa-caret-right"></i> Tiene sello Q : {% if guia.registro.es_sello_q_registro%} Si {% else %} No {% endif %}</li>
                  </ul>
                  

                </div>
                </div>
                </div>

             </div>

             <h1 class="classic-title"> Tours </h1>
             {% for tour in guia.tour.all %}
                <div class="panel panel-default">
                <div class="panel-heading">
                <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse-4">
                <i class="fa fa-angle-up control-icon"></i>
                <i class="fa fa-info"></i> Tour: {{tour.nombre_tour}} {% if tour.es_oferta %} ***** OFERTA ***** {% endif %}
                </a>
                </h4>
                </div>
                <div id="collapse-4" class="panel-collapse collapse in">
                <div class="panel-body">
                  <div class="row">
                      <dir class="col-md-4">
                      <a href="{% url 'cicerotwebapp:GetTour' tour.id %}">
                        <img src="{{tour.multimedia_set.all.0.archivo_multimedia.url}}">
                      </a>
                      </dir>
                      <dir class="col-md-8">
                          <ul>
                             <li><i class="fa fa-caret-right"></i> Nombre Tour {{tour.nombre_tour}}</li>
                             <li class="descrip"><i class="fa fa-caret-right"></i> Descripción: {{tour.descripcion_tour}}</li>
                             <li><i class="fa fa-caret-right"></i> Capacidad: {{tour.capacidad_tour}} </li>
                             <li><i class="fa fa-caret-right"></i> Precio: ${{tour.precio_tour}}</li>
                             <li><i class="fa fa-caret-right"></i> Tipo Tour: {{tour.tipo_tour.nombre_tipo_tour}}</li>
                             <li><a href="{% url 'cicerotwebapp:GetTour' tour.id %}"> Ver detalle </a></li>
                            </ul>
                      </dir>
                  </div>
                </div>
                </div>
                </div>

             {% endfor %}
            </div>

          </div>

         
        </div>
      </div>
    </div>
    <!-- End content -->
   

{% endblock %}

cicerotwebapp/templates/guias.html
{% extends "home.html" %}
<!-- field atributes modificaciones / atributo concreto form.nombre-->
{{ form.media.css }}

{% load static %}

{{ form.media.css }}

{% block content %}

    <!-- Start Page Banner -->
    <div class="page-banner" style="padding:40px 0; background: url(images/slide-02-bg.jpg) center #f9f9f9;">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Guías</h2>
            <p>Buscador de guías</p>
          </div>
          <div class="col-md-6">
            <ul class="breadcrumbs">
              <li><a href="{% url 'cicerotwebapp:home' %}">Home</a></li>
              <li>Guías</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- End Page Banner -->


    <!-- Start Content -->
    <div id="content">
      <div class="container">
        <div class="page-content">

          <!-- Classic Heading -->
          <h4 class="classic-title"><span>Nuestros guías: Busca a tu guía turístico</span></h4>
          <div class="widget widget-search">
            <form role="form" class="contact-form" id="form" method="GET" action="">
              <input placeholder="Lugares, nombre, comunas, tipo de guía, etc ..." type="search" name="search" value="{{ request.GET.search }}">
              <button class="search-btn" type="submit"><i class="fa fa-search"></i></button>
            </form>
          </div>

          <!-- Start Team Members -->
          <div class="row">
          {% for guia in guias %}
            <!-- Start Memebr 1 -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="team-member">
                <a href="{% url 'cicerotwebapp:GetGuia' guia.id %}">
                <!-- Memebr Photo, Name & Position -->
                <div class="member-photo">
                  <img alt="" src="{{guia.usuario.multimedia_set.all.0.archivo_multimedia.url}}" />
                  <div class="member-name">{{guia.usuario.first_name}} {{guia.usuario.last_name}} - {{guia.clasificacion_guia}} <i class="fa fa-star"></i> <span>Guía Turístico</span></div>
                </div>
                </a>
                <!-- Memebr Words -->
                <div class="member-info">
                  <p class="descrip">{{guia.descripcion_guia}}</p>...
                </div>
                <!-- Memebr Social Links -->
                <div class="member-socail">
                  <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                  <a class="gplus" href="#"><i class="fa fa-google-plus"></i></a>
                  <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                  <a class="flickr" href="#"><i class="fa fa-flickr"></i></a>
                  <a class="mail" href="#"><i class="fa fa-envelope"></i></a>
                </div>
                <div class="member-info">
                  Etiquetas: {% for tag in guia.tags.all %}
                    <a href="#">{{tag.texto_tag}}</a>,
                  {% endfor %}
                </div>
                <div class="member-info">
                  Tipo de Guía: {% for tipo in guia.tipos_guia.all %}
                    <a href="#">{{tipo.nombre_tipo_guia}}</a>,
                  {% endfor %}
                </div>
              </div>
            </div>
            <!-- End Memebr 1 -->
            {% endfor %}
          </div>
          <!-- End Team Members -->

        </div>
      </div>
    </div>
    <!-- End content -->
    
    
{% endblock %}